import { context } from "esbuild";
import { writeFile } from "node:fs/promises";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/`;

const production = process.argv.includes("production");
const build = await context({
  banner: { js: banner },
  entryPoints: ["src/excalibrain-main.ts"],
  outfile: "main.js",
  bundle: true,
  platform: "browser",
  format: "cjs",
  target: "es2022",
  external: [
    "obsidian", "electron",
    "@codemirror/autocomplete", "@codemirror/collab", "@codemirror/commands",
    "@codemirror/language", "@codemirror/lint", "@codemirror/search",
    "@codemirror/state", "@codemirror/view",
    "@lezer/common", "@lezer/highlight", "@lezer/lr",
  ],
  define: {
    "process.env.NODE_ENV": JSON.stringify(production ? "production" : "development"),
  },
  sourcemap: production ? false : "inline",
  minify: production,
  treeShaking: true,
  metafile: true,
  logLevel: "info",
});

if (production) {
  try {
    const result = await build.rebuild();
    await writeFile("build-meta.json", JSON.stringify(result.metafile, null, 2));
  } finally {
    await build.dispose();
  }
} else {
  await build.watch();
}
